#!/usr/bin/env bash
#
# load scripting additions (optional)

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


#osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'
# default layout (can be bsp, stack or float)
yabai -m config layout bsp

yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 8
yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off


# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize


# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap



yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^karabiner-Elements$" manage=off
yabai -m rule --add app="^zoom\.us$" manage=off
yabai -m rule --add app="^Finder$" manage=off

yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555

yabai -m window --toggle border
yabai -m rule --add app=Terminal border=off




# Spaces

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 code 
setup_space 2 web 
setup_space 3 slack
setup_space 4 media


#
# yabai -m rule --add app="^Alacritty$" space=^1
# yabai -m rule --add app="^Arc$" space=^2
# yabai -m rule --add app="^Chrome$" space=^2
# yabai -m rule --add app="^Slack$" space=^3
# yabai -m rule --add app="^Bruno$" space=^5
# yabai -m rule --add app="^Obsidian$" space=^5
